# Generated by Django 5.0.1 on 2024-01-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youcare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientappointment',
            name='appointment_id',
        ),
    ]
