# Generated by Django 5.0.1 on 2024-01-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youcare', '0002_remove_patientappointment_appointment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientappointment',
            name='assigned_doctor',
        ),
        migrations.AddField(
            model_name='patientappointment',
            name='assigned_doctors',
            field=models.ManyToManyField(related_name='appointments', to='youcare.doctor'),
        ),
    ]
