# Generated by Django 5.0.1 on 2024-01-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youcare', '0003_remove_patientappointment_assigned_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientappointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
